# -*- coding: utf-8 -*-
"""AI Home Task+class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Urk7De8E1nPS7o6f8H-wc6cHJaaiSF8r

#**Home Task Notebook By Pari Gurbaksh Lal (2312169)**

#SCROLL DOWN FOR HOME TASK
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv('/content/train.csv')
df.head()

df.head(7)

df.tail()

df.shape

df.describe()

df.info()

df = df.drop(columns=['Ticket', 'Cabin', 'Name'])

df['Embarked'].unique()

df['Embarked'].nunique()

df['Embarked'] = df['Embarked'].fillna('S')

df['Embarked'] = df['Embarked'].map({'S':1, 'C':2, 'Q':3})

df['Sex'] = df['Sex'].map({'male': 0, 'female':1})

#handling null values
df.info()

df['Embarked'].isnull().sum()

df.info()
df['Age'] = df['Age'].fillna(29)

df.duplicated().sum()
#df.drop_duplicate()

#handling outliers
import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(x = df['Fare'])
plt.show()

df = df[df['Fare'] < 300]
df.info()

"""Normalisation and Standarization"""

from sklearn.preprocessing import MinMaxScaler, StandardScaler

Norm = MinMaxScaler()
Stand = StandardScaler()

#norm on age
df['Age'] = Norm.fit_transform(df[['Age']])
#stand on fare
df['Fare'] = Stand.fit_transform(df[['Fare']])

df

"""# (**Home Task STARTED)**

# 1. Use a bar plot to show the number of people that survived and number of people that did not survive.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#df["Survived"].value_counts().plot(kind='bar') in pandas
sns.countplot(x = 'Survived', data = df)
plt.title("Number of survivals V/S Not survived")
plt.xlabel("Survived(0 = No, 1 = Yes)")
plt.ylabel("Number of people")
plt.show()

"""# 2. Plot the number of people that survived by both Class and Gender"""

df['Pclass'].value_counts()

survivors = df[df['Survived'] == 1]
sns.countplot(x = 'Pclass', hue='Sex', data=survivors)
plt.title("number of survivors by Class and Gender")
plt.xlabel("Class")
plt.ylabel("Number of people ")
plt.legend(title= "Gender")
plt.show()

"""# 3. Can we remove outliers or apply normalization/standardization on complete table?
outliers:
no not on the entire table , outliers are for some columns like age and fare that are numeric columns and not apply on the columns like Sex, Pclass, Survived
solution: remove outliers column by column for numeric only

Normalization and standarization should only apply on the numeric columns not on complete table otherwise categorical columns are meaningless numbers to scale

# What is the difference between the Pandas series and dataframe?

**Pandas series** is one dimensional like a single column of data, has a fixed size it's focus is element-wise, elements has same datatypes and **dataframe** is 2- dimensional data structure in the form of dataset (spread sheet or SQL Table), columns can have different datatypes and it is designed for column-wise operations and advanced data analysis it is more powerful than series.

#  Delete or Add column in Dataframe. (Also define concept of Axis)
Axis in Pandas defines the direction of data operation. at axis 1 columns(horizentally) will be removed and at axis = 1 rows(Vertically) will be removed
"""

#delete columns that has null values
df = df.drop('Name', axis=1 )
df = df.drop('Ticket' , axis=1)
df = df.drop('Cabin' , axis=1)

#for adding column: we have to add values according to the dataset length so it will not occur any error
# Age * 2 because of the length matching of age for new values of New column (NewAge)

#add
df['NewAge'] = df['Age'] * 2
#delete
df = df.drop('NewAge', axis=1)

df

"""# How do we change column names in Dataframe?
through rename keyword
"""

df = df.rename(columns={'Sex': 'Gender'})
df

"""# Apply logical conditions to print values greater than certain threshold in any one column.

Logical conditions in Pandas always select rows, not just the column. If you want only one column after filtering, you have to select the column explicitly.
"""

df[df['PassengerId'] > 30]

"""# What is the sort function in pandas? Perform ascending and descending sort for any one column.
 in pandas is DataFrame.sort_values(), which sorts a DataFrame by the values in one or more columns. By default, it sorts in ascending order, it's essensial for organizing data for easier analysis.

 Useful for organizing data to find highest, lowest, or just to view in order.

 **by:** keyword for column you want to sort

ascending=True means sort in ascending order (default)

ascending=False means sort in descending order
"""

# descending sort:
df.sort_values(by='Age', ascending=False)

"""Ascending sort (smallest to largest)"""

df_asc = df.sort_values(by='Age', ascending=True)
print(df_asc[['PassengerId','Age']]) # DataFrame sorted by Age from youngest to oldest

"""Descending sort (largest to smallest)"""

df_desc = df.sort_values(by='Age', ascending=False)
print(df_desc[['PassengerId','Age']]) #DataFrame sorted by Age from oldest to youngest

"""# How do I access data in a dataframe? (Explore loc and iloc options)

In Pandas, loc and iloc are the primary methods for selecting data from a DataFrame. The fundamental difference is that loc is label-based (using names), while iloc is integer-based (using positions).
"""

# Access multiple columns
print(df[['Age', 'Fare']])

# Access single column
print(df['Age'])

# Access rows 0 to 5
#also called as slicing
print(df[0:5])

# Using loc (label-based)
print(df.loc[0:5, ['Age','Fare']])

# Using iloc (position-based)
print(df.iloc[0:5, 2:5])

# Access a single row by index label
df.loc[0]

# Access multiple rows and columns
df.loc[0:5, ['Age', 'Fare']]

# Access first row
df.iloc[0]

# Access first 5 rows, columns 3 to 5
df.iloc[0:5, 2:5]

"""# Create Excel file with multiple sheets and than load 3rd sheet in Excel file"""

import pandas as pd

# Create example DataFrames for each sheet
df1 = pd.DataFrame({'PassengerId':[1,2,3,4], 'Name':['Alice','Bob','Charlie','Diana'], 'Gender':['F','M','M','F'], 'Age':[25,30,35,28]})
df2 = pd.DataFrame({'TicketNo':[1001,1002,1003,1004], 'Pclass':[1,2,3,1], 'Fare':[150,80,40,200]})
df3 = pd.DataFrame({'PassengerId':[1,2,3,4], 'Embarked':['C','Q','S','C'], 'Destination':['London','Paris','New York','Berlin']})

# Create Excel file with multiple sheets
excel_file = 'example.xlsx'
with pd.ExcelWriter(excel_file) as writer:
    df1.to_excel(writer, sheet_name='Sheet1', index=False)
    df2.to_excel(writer, sheet_name='Sheet2', index=False)
    df3.to_excel(writer, sheet_name='Sheet3', index=False)

print("Excel file with 3 sheets created successfully!")

# Load the 3rd sheet (Sheet3) using index
df_third = pd.read_excel(excel_file, sheet_name=2)  # 0-based indexing
df_third

df_third.head(2)

