# -*- coding: utf-8 -*-
"""Assignment part.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Za9vWJT-Wa1uFxws5ZPr-oEnILGH48A7

# Assignment Part
Target variable: target variable
"""

import pandas as pd

df = pd.read_csv("/content/Pakistan Largest Ecommerce Dataset.csv")

df.head()

df.tail(7)

"""# Data Preprocessing: [1 Mark]
# Remove all unused columns (if any)

SO THERE ARE UNNAMED COLUMNS SO WE HAVE TO REMOVE THEM First
"""

df= df.drop(columns=['Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25'])

df.info()

"""Unused columns :"""

df = df.drop(columns=['item_id', 'increment_id', 'Customer ID'])

"""Also remove text-heavy / unnecessary:

already removed
"""

df = df.drop(columns=['created_at', 'Working Date', 'M-Y', 'Customer Since'])
df = df.drop(['status'], axis=1) #data leakage
df = df.drop(['FY', 'Year'], axis=1) #useless no variation in values
df = df.drop(['sku', 'sales_commission_code'], axis=1)  #high unique values

"""# Handle Null values (decide whether to remove column, add ‘0’ or mean of feature)"""

df.isnull().sum()

"""There are columns that are missing sku has 5 missing values and there are other columns that has 1 missing values we have to fill them.

"""

df['payment_method'] = df['payment_method'].fillna('cod')

df['BI Status'] = df['BI Status'].fillna('Unknown')

df = df.fillna(0)

"""# Handle duplicates (If any remove them)

"""

df.duplicated().sum()

len(df)

df = df.drop_duplicates()

df.duplicated().sum()

df

"""# Handle Categorical Features"""

df['BI Status'] = df['BI Status'].replace('#REF!', 'Unknown')

df['category_name_1'] = df['category_name_1'].astype('category').cat.codes #.cat.codes for Converts text into numbers for usable data analysis

df['payment_method'] = df['payment_method'].astype('category').cat.codes

df['BI Status'] = df['BI Status'].astype('category').cat.codes

"""Categorical features such as category_name_1, payment_method, and BI Status contained textual data.
These were converted into numerical values using label encoding so that they could be used for analysis and correlation.
Each unique category was assigned a numeric code automatically.
"""

df.head()

"""#Find correlations (which features are redundant?, which features align most with Target  variable, give 5 most important features, plot scatter plot for any two important features.)

Some columns contained numeric values stored as text (e.g., with commas). These were cleaned and converted into numeric format before performing correlation analysis
"""

#Find Correlation with Target (grand_total)
df.corr()['grand_total'].sort_values(ascending=False)

# top 5 important features
df.corr(numeric_only=True)['grand_total'].sort_values(ascending=False).head(6)

"""Top 5 Important Features

The top 5 features most correlated with the target variable (grand_total) are:

MV (highest correlation)

price

payment_method

qty_ordered

discount_amount

MV is highly correlated with the target variable and may be redundant as it represents similar information.

MV and price are the most aligned features with the target variable.
"""

df.plot.scatter(x= 'price', y='grand_total', title='price V/S grand_total')

"""A scatter plot was created between price and grand total. It shows a positive relationship, meaning as price increases, the total amount also increases."""

df.plot.scatter(x= 'qty_ordered', y= 'grand_total' , title= 'Quantity ordered V/S Grand total')

"""# Handle Outliers"""

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler, StandardScaler
Scaler = MinMaxScaler()
Stand = StandardScaler()
num_cols = ['price', 'qty_ordered', 'grand_total', 'discount_amount', ' MV ']
df[num_cols] = Scaler.fit_transform(df[num_cols])

"""Min-Max normalization was applied to all numerical features to bring them into a common scale."""

df.describe()



"""# **DATA** **ANALYTICS**

# What is the best-selling category?
"""

